# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


def react

  
end

def flutter
  flutter_application_path = '../flutter_mudule'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
  
end


target 'laboratory' do
  
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  use_frameworks!
  
#  react
  flutter

  pod 'ZymeWidget', :path => '../ZymeWidget'#, :subspecs => ['NetWorkEngine']
  pod 'SwiftyJSON','~> 5.0'
  pod 'SwiftDate','~> 6.0.3'
#  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'ReactiveObjC'

end
