# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


def react

  
end


target 'lab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
#  react

  pod 'HzyWidget', :path => '../HzyWidget'#, :subspecs => ['NetWorkEngine']
  pod 'SwiftyJSON','~> 5.0'
  pod 'SwiftDate','~> 6.0.3'
#  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'ReactiveObjC'

end
